In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv('C:/Users/lin87/Desktop/dataF.csv')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('評估',axis = 1)
y = df['評估']

In [7]:
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 101)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
predictions = dtree.predict(x_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

       10001       0.58      0.66      0.62        32
       10002       0.25      0.50      0.33         4
       10003       0.68      0.60      0.64        73
       10004       0.38      0.50      0.43        12
       10005       0.39      0.32      0.35        22

   micro avg       0.56      0.56      0.56       143
   macro avg       0.45      0.52      0.47       143
weighted avg       0.57      0.56      0.56       143

[[21  1  7  1  2]
 [ 0  2  1  1  0]
 [13  4 44  4  8]
 [ 1  0  4  6  1]
 [ 1  1  9  4  7]]


In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
rfc = RandomForestClassifier(n_estimators=100)

#從訓練組資料中建立隨機森林模型
rfc.fit(X_train, y_train)

#預測測試組的駝背是否發生
rfc_pred = rfc.predict(x_test)

In [16]:
print(confusion_matrix(y_test,rfc_pred))

#利用classification_report來看precision、recall、f1-score、support
print(classification_report(y_test,rfc_pred))

[[26  0  6  0  0]
 [ 0  2  1  1  0]
 [11  0 58  2  2]
 [ 2  0  5  3  2]
 [ 3  0  8  5  6]]
              precision    recall  f1-score   support

       10001       0.62      0.81      0.70        32
       10002       1.00      0.50      0.67         4
       10003       0.74      0.79      0.77        73
       10004       0.27      0.25      0.26        12
       10005       0.60      0.27      0.37        22

   micro avg       0.66      0.66      0.66       143
   macro avg       0.65      0.53      0.55       143
weighted avg       0.66      0.66      0.65       143



In [18]:
from sklearn import neighbors

In [19]:
clf = neighbors.KNeighborsClassifier()

In [20]:
cclf = clf.fit(X_train,y_train)

In [21]:
clf_pred = clf.predict(x_test)

In [22]:
print(confusion_matrix(y_test,clf_pred))

#利用classification_report來看precision、recall、f1-score、support
print(classification_report(y_test,clf_pred))

[[24  0  8  0  0]
 [ 0  2  1  1  0]
 [10  4 56  1  2]
 [ 3  1  5  1  2]
 [ 4  0  9  0  9]]
              precision    recall  f1-score   support

       10001       0.59      0.75      0.66        32
       10002       0.29      0.50      0.36         4
       10003       0.71      0.77      0.74        73
       10004       0.33      0.08      0.13        12
       10005       0.69      0.41      0.51        22

   micro avg       0.64      0.64      0.64       143
   macro avg       0.52      0.50      0.48       143
weighted avg       0.64      0.64      0.62       143

